const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v||0);
const seedProducts=[{"code":"ROB0002","name":"MÓDULO DE RELÉ DE 1 CANAL 5V SEM ISOLAMENTO OPTOACOPLADOR","stock":5025,"incoming":0,"price":3.25,"image":"assets/produtos/ROB0002.jpeg"},{"code":"ROB0006","name":"DIMMER 2000W 90-220V","stock":956,"incoming":0,"price":7.89,"image":"assets/produtos/ROB0006.jpeg"},{"code":"ROB0011","name":"MÓDULO RELE 4 CANAIS 5V OPTOACOPLADOR","stock":570,"incoming":300,"price":11.89,"image":"assets/produtos/ROB0011.jpeg"},{"code":"ROB0012","name":"STEPPER MOTOR DRIVER PARA IMPRESSORA 3D DRV8825","stock":80,"incoming":0,"price":7.89,"image":"assets/produtos/ROB0012.jpeg"},{"code":"ROB0014","name":"TECLADO MATRICIAL MEMBRANA 4X4 16 TECLAS","stock":300,"incoming":500,"price":3.99,"image":"assets/produtos/ROB0014.png"},{"code":"ROB0017","name":"TRANSMISSOR E RECEPTOR RF433 MHZ WL","stock":0,"incoming":351,"price":5.49,"image":"assets/produtos/ROB0017.jpeg"},{"code":"ROB0019","name":"MÓDULO FONTE 5V700MA (3,5W) AC-DC 220V","stock":95,"incoming":0,"price":9.89,"image":"assets/produtos/ROB0019.jpeg"},{"code":"ROB0021","name":"MÓDULO RELÉ DE 8 CANAIS 5V","stock":333,"incoming":0,"price":21.89,"image":"assets/produtos/ROB0021.jpeg"},{"code":"ROB0024","name":"ADAPTADOR USB-SERIAL TTL PL2303","stock":250,"incoming":100,"price":6.09,"image":"assets/produtos/ROB0024.jpeg"},{"code":"ROB0025","name":"ADAPTADOR USB-SERIAL TTL CONVERSOR CP2102 5 PINOS","stock":0,"incoming":97,"price":10.89,"image":"assets/produtos/ROB0025.jpeg"},{"code":"ROB0026","name":"MÓDULO ADS1115 ADC de 16 bits - 4 canais","stock":45,"incoming":0,"price":12.89,"image":"assets/produtos/ROB0026.png"},{"code":"ROB0027","name":"KIT CABO JACARÉ X10 UNIDADES","stock":2953,"incoming":500,"price":5.89,"image":"assets/produtos/ROB0027.jpeg"},{"code":"ROB0028","name":"SENSOR DE UMIDADE E TEMPERATURA AM2302 - DHT22","stock":175,"incoming":0,"price":7.29,"image":"assets/produtos/ROB0028.jpeg"},{"code":"ROB0031","name":"ANTENA WIFI 3DBI 2.4Ghz","stock":39,"incoming":300,"price":6.49,"image":"assets/produtos/ROB0031.jpeg"},{"code":"ROB0032","name":"PLACA LEONARDO R3 + CABO USB","stock":416,"incoming":0,"price":39.89,"image":"assets/produtos/ROB0032.jpeg"}];
const defaultSellers=[{id:'s1',name:'Equipe Comercial Nightech',email:'comercial@nightech.com.br',phone:'(11) 93060-9734'}];
const db={
 get(k,d){try{return JSON.parse(localStorage.getItem('nt_'+k))??d}catch{return d}},
 set(k,v){localStorage.setItem('nt_'+k,JSON.stringify(v))}
};
const CATALOG_VERSION='xlsx-karina-v1';
if(db.get('catalog_version')!==CATALOG_VERSION){
  db.set('products',seedProducts);
  const validCodes=new Set(seedProducts.map(p=>p.code));
  const oldCart=db.get('cart',{});
  db.set('cart',Object.fromEntries(Object.entries(oldCart).filter(([code])=>validCodes.has(code))));
  db.set('catalog_version',CATALOG_VERSION);
}
if(!db.get('sellers'))db.set('sellers',defaultSellers); if(!db.get('users'))db.set('users',[{id:'admin',name:'Administrador Nightech',email:'admin@nightech.local',password:'admin123',role:'admin'}]); if(!db.get('promo'))db.set('promo',{discount:0,freeShipping:false});
let products=db.get('products',[]), cart=db.get('cart',{}), currentUser=db.get('session',null), authMode='login';
let activeQuery='', visibleLimit=48;
function placeholderImage(p){const label=encodeURIComponent((p.code||'NIGHTECH').slice(0,16));return `data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns=%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width=%22640%22%20height=%22420%22%20viewBox=%220%200%20640%20420%22%3E%3Crect%20width=%22640%22%20height=%22420%22%20fill=%22%23eef2f6%22%2F%3E%3Cpath%20d=%22M250%20158h140v104H250z%22%20fill=%22%23dbe4ee%22%2F%3E%3Ccircle%20cx=%22320%22%20cy=%22210%22%20r=%2235%22%20fill=%22%2300a8e8%22%20opacity=%22.35%22%2F%3E%3Ctext%20x=%22320%22%20y=%22325%22%20font-family=%22Arial%22%20font-size=%2228%22%20font-weight=%22700%22%20text-anchor=%22middle%22%20fill=%22%230077b6%22%3E${label}%3C%2Ftext%3E%3Ctext%20x=%22320%22%20y=%22360%22%20font-family=%22Arial%22%20font-size=%2218%22%20text-anchor=%22middle%22%20fill=%22%23667085%22%3EFoto%20em%20breve%3C%2Ftext%3E%3C%2Fsvg%3E`}
function productImage(p){return p.image||p.imageUrl||placeholderImage(p)}
function getFilteredProducts(){let list=[...products],q=activeQuery.toLowerCase().trim(),f=$('#stockFilter').value,s=$('#sortSelect').value;if(q)list=list.filter(p=>(`${p.code||''} ${p.name||''}`).toLowerCase().includes(q));if(f==='available')list=list.filter(p=>p.stock>0);if(f==='incoming')list=list.filter(p=>p.incoming>0);if(s==='priceAsc')list.sort((a,b)=>a.price-b.price);if(s==='priceDesc')list.sort((a,b)=>b.price-a.price);if(s==='name')list.sort((a,b)=>a.name.localeCompare(b.name));if(s==='code')list.sort((a,b)=>a.code.localeCompare(b.code));return list}
function renderCatalog(){let list=getFilteredProducts(),shown=list.slice(0,visibleLimit);$('#catalog').innerHTML=shown.length?shown.map(p=>{let q=cart[p.code]||0;return `<article class="product-card ${q?'selected':''}" data-code="${esc(p.code)}"><div class="product-image-wrap"><img class="product-image" src="${esc(productImage(p))}" alt="${esc(p.name)}" loading="lazy" onerror="this.onerror=null;this.src='${placeholderImage(p)}'"></div><span class="code">${esc(p.code)}</span><h3>${esc(p.name)}</h3><span class="stock ${p.stock>0?'ok':''}">${p.stock>0?p.stock+' em estoque':p.incoming>0?'Sem estoque • previsão '+p.incoming:'Indisponível'}</span><div class="price">${money(p.price)}</div><div class="product-actions">${q?`<div class="qty"><button data-act="minus" aria-label="Diminuir quantidade">−</button><input value="${q}" inputmode="numeric" aria-label="Quantidade"><button data-act="plus" aria-label="Aumentar quantidade">+</button></div><button class="ghost select-btn" data-act="remove">Remover</button>`:`<button class="primary select-btn" data-act="add">Selecionar</button>`}</div></article>`}).join(''):'<div class="empty-results"><strong>Nenhum produto encontrado.</strong><span>Tente outro código, palavra ou ajuste os filtros.</span></div>';$('#productCount').textContent=list.length;$('#loadMoreBtn').classList.toggle('hidden',shown.length>=list.length);$('#loadMoreBtn').textContent=`Carregar mais produtos (${shown.length} de ${list.length})`;let status=$('#searchStatus');status.classList.toggle('hidden',!activeQuery);status.innerHTML=activeQuery?`Busca por <b>${esc(activeQuery)}</b>: ${list.length} resultado(s). <button type="button" id="inlineClearSearch">Ver todos</button>`:'';updateTotals()}
function runSearch(){activeQuery=$('#searchInput').value.trim();visibleLimit=48;$('#clearSearchBtn').classList.toggle('hidden',!activeQuery);renderCatalog()}

function updateTotals(){let lines=Object.entries(cart).map(([code,qty])=>({p:products.find(x=>x.code===code),qty})).filter(x=>x.p);let count=lines.reduce((a,x)=>a+x.qty,0),subtotal=lines.reduce((a,x)=>a+x.p.price*x.qty,0);$('#cartCount').textContent=count;$('#selectedCount').textContent=count;$('#subtotalTop').textContent=money(subtotal);let headerTotal=$('#headerOrderTotal');if(headerTotal)headerTotal.textContent=money(subtotal);db.set('cart',cart)}
$('#catalog').addEventListener('click',e=>{let card=e.target.closest('.product-card');if(!card)return;let code=card.dataset.code,act=e.target.dataset.act;if(!act)return;if(act==='add')cart[code]=1;if(act==='plus')cart[code]=(cart[code]||0)+1;if(act==='minus'){cart[code]=Math.max(0,(cart[code]||0)-1);if(!cart[code])delete cart[code]}if(act==='remove')delete cart[code];renderCatalog()});
$('#catalog').addEventListener('change',e=>{if(!e.target.matches('.qty input'))return;let code=e.target.closest('.product-card').dataset.code,q=Math.max(0,parseInt(e.target.value||0));if(q)cart[code]=q;else delete cart[code];renderCatalog()});
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();runSearch()});$('#clearSearchBtn').onclick=()=>{$('#searchInput').value='';activeQuery='';visibleLimit=48;$('#clearSearchBtn').classList.add('hidden');renderCatalog()};$('#searchStatus').onclick=e=>{if(e.target.id==='inlineClearSearch')$('#clearSearchBtn').click()};$('#loadMoreBtn').onclick=()=>{visibleLimit+=48;renderCatalog()};['stockFilter','sortSelect'].forEach(id=>$('#'+id).addEventListener('input',()=>{visibleLimit=48;renderCatalog()}));$('#searchInput').addEventListener('search',()=>{if(!$('#searchInput').value)$('#clearSearchBtn').click()});
function syncAuthUI(){currentUser=db.get('session',null);$('#authBtn').textContent=currentUser?'Sair':'Entrar';$('#historyBtn').classList.toggle('hidden',!currentUser);$('#adminBtn').classList.toggle('hidden',currentUser?.role!=='admin')}
$('#authBtn').onclick=()=>{if(currentUser){db.set('session',null);syncAuthUI();return}openAuth()};
function openAuth(){authMode='login';$('#authTitle').textContent='Entrar';$('#nameField').parentElement.style.display='none';$('#phoneField').parentElement.style.display='none';$('#docField').parentElement.style.display='none';$('#toggleAuth').textContent='Criar cadastro';$('#authDialog').showModal()}
$('#toggleAuth').onclick=()=>{authMode=authMode==='login'?'register':'login';let reg=authMode==='register';$('#authTitle').textContent=reg?'Criar cadastro de cliente':'Entrar';['nameField','phoneField','docField'].forEach(id=>$('#'+id).parentElement.style.display=reg?'block':'none');$('#toggleAuth').textContent=reg?'Já tenho cadastro':'Criar cadastro'};
$('#authForm').addEventListener('submit',e=>{e.preventDefault();let users=db.get('users',[]),email=$('#emailField').value.trim().toLowerCase(),pass=$('#passwordField').value;if(authMode==='register'){if(users.some(u=>u.email===email))return alert('E-mail já cadastrado.');let u={id:crypto.randomUUID(),name:$('#nameField').value.trim(),email,password:pass,phone:$('#phoneField').value.trim(),doc:$('#docField').value.trim(),role:'client'};users.push(u);db.set('users',users);db.set('session',u)}else{let u=users.find(u=>u.email.toLowerCase()===email&&u.password===pass);if(!u)return alert('E-mail ou senha inválidos.');db.set('session',u)}$('#authDialog').close();syncAuthUI()});
function openCart(){let lines=cartLines();if(!lines.length)return alert('Selecione ao menos um produto.');$('#cartItems').innerHTML=lines.map(x=>`<div class="cart-row"><div><b>${x.p.code}</b> ${x.p.name}<small>${money(x.p.price)} × ${x.qty}</small></div><strong>${money(x.p.price*x.qty)}</strong><button class="ghost" data-remove="${x.p.code}">×</button></div>`).join('');let sellers=db.get('sellers',[]);$('#sellerSelect').innerHTML=sellers.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');updateCartSummary();$('#cartDialog').showModal()}
function cartLines(){return Object.entries(cart).map(([code,qty])=>({p:products.find(x=>x.code===code),qty})).filter(x=>x.p)}
function totals(){let subtotal=cartLines().reduce((a,x)=>a+x.p.price*x.qty,0),promo=db.get('promo',{discount:0,freeShipping:false}),discount=subtotal*(Number(promo.discount)||0)/100,total=subtotal-discount;return{subtotal,discount,total,promo}}
function updateCartSummary(){let t=totals();$('#subtotalCart').textContent=money(t.subtotal);$('#discountCart').textContent='− '+money(t.discount);$('#shippingCart').textContent=t.promo.freeShipping?'GRÁTIS':'A combinar';$('#totalCart').textContent=money(t.total)}
$('#cartBtn').onclick=openCart;$('#closeCart').onclick=()=>$('#cartDialog').close();$('#cartItems').onclick=e=>{let code=e.target.dataset.remove;if(code){delete cart[code];db.set('cart',cart);$('#cartDialog').close();renderCatalog();if(Object.keys(cart).length)openCart()}};
$('#generateOrder').onclick=()=>{currentUser=db.get('session',null);if(!currentUser){$('#cartDialog').close();openAuth();return alert('Faça login ou crie seu cadastro antes de gerar o pedido.')}let sellers=db.get('sellers',[]),seller=sellers.find(s=>s.id===$('#sellerSelect').value)||sellers[0],lines=cartLines(),t=totals(),now=new Date(),order={id:'NT-'+now.getTime().toString().slice(-8),createdAt:now.toISOString(),customer:{name:currentUser.name,email:currentUser.email,phone:currentUser.phone||'',doc:currentUser.doc||''},seller,lines:lines.map(x=>({...x.p,qty:x.qty,lineTotal:x.p.price*x.qty})),subtotal:t.subtotal,discount:t.discount,total:t.total,freeShipping:t.promo.freeShipping,notes:$('#orderNotes').value};let orders=db.get('orders',[]);orders.unshift(order);db.set('orders',orders);makePdf(order);cart={};db.set('cart',cart);$('#cartDialog').close();renderCatalog();alert('Pedido gerado e salvo no histórico deste protótipo.');};
function makePdf(o){
  const rows=o.lines.map(l=>`<tr><td>${esc(l.code)}</td><td>${esc(l.name)}</td><td>${l.qty}</td><td>${money(l.price)}</td><td>${money(l.lineTotal)}</td></tr>`).join('');
  const html=`<!doctype html><html><head><meta charset="utf-8"><title>${o.id}</title><style>@page{size:A4;margin:14mm}body{font-family:Arial,sans-serif;color:#111827;font-size:12px}h1{font-size:22px;margin:0 0 8px}.meta{display:flex;justify-content:space-between;border-bottom:2px solid #111827;padding-bottom:10px;margin-bottom:14px}.cols{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin:16px 0}.box h3{font-size:11px;margin:0 0 6px}.box p{margin:3px 0}table{width:100%;border-collapse:collapse;margin-top:14px}th,td{padding:7px 5px;border-bottom:1px solid #d1d5db;text-align:left}th:nth-child(3),td:nth-child(3){text-align:center}th:nth-child(4),td:nth-child(4),th:nth-child(5),td:nth-child(5){text-align:right}.totals{margin-left:auto;width:280px;margin-top:16px}.totals div{display:flex;justify-content:space-between;padding:4px}.grand{font-size:16px;font-weight:bold;border-top:2px solid #111827;margin-top:4px}.footer{position:fixed;bottom:0;font-size:9px;color:#6b7280}.noprint{margin:15px 0;padding:10px;background:#eef6ff;border-radius:8px}@media print{.noprint{display:none}}</style></head><body><div class="noprint"><b>Pedido pronto.</b> Na janela de impressão escolha <b>Salvar como PDF</b>. Em celulares, use a opção de compartilhar/salvar PDF disponível no sistema.</div><h1>NIGHTECH — PEDIDO DE COMPRA</h1><div class="meta"><span><b>Pedido:</b> ${o.id}</span><span><b>Data:</b> ${new Date(o.createdAt).toLocaleString('pt-BR')}</span></div><div class="cols"><div class="box"><h3>COMPRADOR</h3><p>${esc(o.customer.name||'-')}</p><p>${esc(o.customer.email||'-')}</p><p>${esc(o.customer.phone||'')}</p><p>${esc(o.customer.doc||'')}</p></div><div class="box"><h3>VENDEDOR / CONSULTOR</h3><p>${esc(o.seller?.name||'-')}</p><p>${esc(o.seller?.email||'-')}</p><p>${esc(o.seller?.phone||'')}</p></div></div><table><thead><tr><th>Código</th><th>Produto</th><th>Qtd.</th><th>Unitário</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table><div class="totals"><div><span>Subtotal</span><b>${money(o.subtotal)}</b></div><div><span>Desconto</span><b>− ${money(o.discount)}</b></div><div><span>Frete</span><b>${o.freeShipping?'GRÁTIS':'A combinar'}</b></div><div class="grand"><span>Total</span><b>${money(o.total)}</b></div></div>${o.notes?`<h3>Observações</h3><p>${esc(o.notes)}</p>`:''}<div class="footer">Nightech • Rua Piramboia, 1082 - Jardim Stella, Santo André - SP • comercial@nightech.com.br</div><script>setTimeout(()=>window.print(),250)<\/script></body></html>`;
  const w=window.open('','_blank'); if(!w){alert('Permita pop-ups para gerar o PDF.');return} w.document.open();w.document.write(html);w.document.close();
}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('#historyBtn').onclick=()=>{let orders=db.get('orders',[]).filter(o=>currentUser?.role==='admin'||o.customer.email===currentUser?.email||o.seller?.email===currentUser?.email);$('#historyList').innerHTML=orders.length?orders.map(o=>`<div class="history-card"><b>${o.id}</b> • ${new Date(o.createdAt).toLocaleString('pt-BR')}<br><span>${o.lines.length} item(ns) • <b>${money(o.total)}</b></span></div>`).join(''):'<p class="muted">Nenhum pedido encontrado.</p>';$('#historyDialog').showModal()};$('#closeHistory').onclick=()=>$('#historyDialog').close();
$('#adminBtn').onclick=()=>{renderAdmin();$('#adminDialog').showModal()};$('#closeAdmin').onclick=()=>$('#adminDialog').close();$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#tab-'+b.dataset.tab).classList.add('active')});
function renderAdmin(){products=db.get('products',[]);$('#adminProducts').innerHTML=products.map(p=>`<div class="admin-line product-admin-line"><img src="${esc(productImage(p))}" alt="" onerror="this.onerror=null;this.src='${placeholderImage(p)}'"><span><b>${esc(p.code)}</b> • ${esc(p.name)} • ${money(p.price)} • estoque ${p.stock}</span><button data-del-product="${esc(p.code)}">Excluir</button></div>`).join('');let sellers=db.get('sellers',[]);$('#adminSellers').innerHTML=sellers.map(s=>`<div class="admin-line"><span><b>${s.name}</b> • ${s.email}</span><button data-del-seller="${s.id}">Excluir</button></div>`).join('');let promo=db.get('promo',{discount:0,freeShipping:false});$('#promoPct').value=promo.discount||0;$('#freeShipping').checked=!!promo.freeShipping}
$('#productForm').onsubmit=async e=>{e.preventDefault();products=db.get('products',[]);let code=$('#pCode').value.trim().toUpperCase();if(products.some(p=>p.code===code))return alert('Código já cadastrado.');let image=$('#pImageUrl').value.trim(),file=$('#pImageFile').files[0];if(file){if(file.size>1200000)return alert('Para este protótipo, use uma imagem de até 1,2 MB. Na versão online não haverá essa limitação local.');image=await fileToDataUrl(file)}products.push({code,name:$('#pName').value.trim(),price:+$('#pPrice').value,stock:+$('#pStock').value,incoming:+$('#pIncoming').value||0,image});db.set('products',products);e.target.reset();renderAdmin();visibleLimit=48;renderCatalog()};
function fileToDataUrl(file){return new Promise((resolve,reject)=>{let r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
$('#sellerForm').onsubmit=e=>{e.preventDefault();let sellers=db.get('sellers',[]);sellers.push({id:crypto.randomUUID(),name:$('#sName').value.trim(),email:$('#sEmail').value.trim(),phone:$('#sPhone').value.trim()});db.set('sellers',sellers);e.target.reset();renderAdmin()};
$('#promoForm').onsubmit=e=>{e.preventDefault();db.set('promo',{discount:+$('#promoPct').value||0,freeShipping:$('#freeShipping').checked});alert('Promoção atualizada.');updateCartSummary()};
$('#adminProducts').onclick=e=>{let code=e.target.dataset.delProduct;if(!code)return;if(confirm('Excluir este produto?')){products=db.get('products',[]).filter(p=>p.code!==code);db.set('products',products);renderAdmin();renderCatalog()}};$('#adminSellers').onclick=e=>{let id=e.target.dataset.delSeller;if(!id)return;if(confirm('Excluir este vendedor?')){db.set('sellers',db.get('sellers',[]).filter(s=>s.id!==id));renderAdmin()}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=20260809-5').catch(()=>{});syncAuthUI();renderCatalog();
